spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:spring-boot-flyway-sample;DB_CLOSE_ON_EXIT=TRUE;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true

  flyway:
    locations: classpath:/db/migration, classpath:/db/dataset
